1. Crea un array de enteros 4X2 e imprime sus atributos. Nota: El elemento debe ser de tipo unsigned int16. Imprime los siguientes atributos: 


- La shape del array.
- Las dimensiones del array.
- El tamaño de cada elemento del array en bytes.

In [2]:
import numpy as np

firstArray = np.empty([4,2], dtype = np.uint16) 
print(firstArray)

print("Attributes")
print("Shape: ", firstArray.shape)
print("Dimensiones: ", firstArray.ndim)
print("Tamaño en bytes de cada elemento: ", firstArray.itemsize)

[[64757 19267]
 [45868 33230]
 [16280  2967]
 [32679     0]]
Attributes
Shape:  (4, 2)
Dimensiones:  2
Tamaño en bytes de cada elemento:  2


2. Crea una matriz de enteros 5X2 de un rango entre 100 y 200 tal que la diferencia entre cada elemento sea 10

In [3]:
sampleArray = np.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


3. A continuación se muestra el array numPy proporcionado. Devuelve un array de elementos tomando la tercera columna de todas las filas.

```
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
```

In [4]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print(sampleArray)

newArray = sampleArray[...,2]
print(newArray)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[33 66 99]


4. Devuelve un array de filas impares y columnas pares dado el siguiente array:

```
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
```


In [5]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print(sampleArray)

newArray = sampleArray[::2, 1::2]
print(newArray)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


5. Crea una matriz de resultados sumando las siguientes dos matrices de NumPy. A continuación, modifica la matriz de resultados calculando el cuadrado de cada elemento.

```
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
```

In [6]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

resultArray  = arrayOne + arrayTwo
print(resultArray)

for num in np.nditer(resultArray, op_flags = ['readwrite']):
    num[...] = num*num
print(resultArray)

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


6. Divide la matriz en cuatro submatrices de igual tamaño. Nota: Crea una matriz de enteros 8X3 de un rango entre 10 y 34 de tal manera que la diferencia entre cada elemento sea 1 y luego divide la matriz en cuatro submatrices de igual tamaño.

In [7]:
sampleArray = np.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

subArrays = np.split(sampleArray, 4) 
print(subArrays)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


7. Ordena el siguiente array de NumPy:
    
- Caso 1: Ordenar el array por la segunda fila
- Caso 2: Ordenar el array por la segunda columna
    
```
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
```

In [8]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print(sampleArray)

sortArrayByRow = sampleArray[:,sampleArray[1,:].argsort()]
print(sortArrayByRow)

sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]
print(sortArrayByColumn)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[73 43 34]
 [12 22 82]
 [66 94 53]]
[[82 22 12]
 [34 43 73]
 [53 94 66]]


8. Imprime el máximo del eje 0 y el mínimo del eje 1 de la siguiente matriz bidimensional:

```
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

```


In [10]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

minOfAxisOne = np.amin(sampleArray, 1) 
print(minOfAxisOne)

maxOfAxisOne = np.amax(sampleArray, 0) 
print(maxOfAxisOne)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[34 12 53]
[82 94 73]


9. Elimina la segunda columna de una matriz dada e inserta la siguiente columna nueva en su lugar.

```
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = numpy.array([[10,10,10]])
```

In [11]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print(sampleArray)

sampleArray = np.delete(sampleArray , 1, axis = 1) 
print(sampleArray)

arr = np.array([[10,10,10]])

sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]
